
DROP TABLE installment_purchase;
DROP TABLE credit_card_purchase;
DROP TABLE bank_purchase;
DROP TABLE installment;
DROP TABLE installment_plan;
DROP TABLE credit_card;
DROP TABLE bank_account;
DROP TABLE service;
DROP TABLE item;
DROP TABLE business;
DROP TABLE individual;
DROP TABLE purchase;
DROP TABLE goods;
DROP TABLE customer;


CREATE TABLE customer(
    id          integer GENERATED BY DEFAULT AS IDENTITY
                (START WITH 101 increment by 1),
    password    varchar(25),
    email       varchar(25),
    address     varchar(75),
    phone_num   char(10),
    primary key (ID));
    
CREATE table goods(
    product_ID  integer GENERATED BY DEFAULT AS IDENTITY,
    price       decimal(10, 2),
    name        varchar(25),
    vendor      varchar(50),
    primary key (product_ID));
    
CREATE table purchase(
    transaction_ID  integer GENERATED BY DEFAULT AS IDENTITY,
    price           varchar(25),
    amount          varchar(10),
    purchase_date   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    customer_ID     integer,
    product_ID      integer,
    primary key (transaction_ID),
    foreign key (customer_ID) references customer(ID),
    foreign key (product_ID) references goods(product_ID)
    );
    
CREATE table individual(
    ID          integer,
    first_name  varchar(15),
    last_name   varchar(15),
    Role        varchar(8),
    primary key (ID),
    foreign key(ID) references customer(ID)
    );
    
CREATE table business(
    ID          integer,
    company_name varchar(30),
    primary key (ID),
    foreign key(ID) references customer(ID)
    );
    
CREATE table item(
    product_ID  integer,
    stock       varchar(4),
    primary key (product_ID),
    foreign key (product_ID) references goods(product_ID)
    );
    
CREATE table service(
    product_ID      integer,
    duration_days   varchar(3),
    primary key (product_ID),
    foreign key (product_ID) references goods(product_ID)
    );

CREATE table bank_account(
    account_ID  integer GENERATED BY DEFAULT AS IDENTITY,
    routing_ID  char(9),
    bank_name   varchar(40),
    balance     decimal(12, 2),
    customer_ID integer,
    primary key (account_ID),
    foreign key (customer_ID) references customer(ID)
    );
    
CREATE table credit_card(
    card_num        char(16),
    security_code   char(3),
    network         varchar(15),
    interest        varchar(5),
    balance         decimal(12, 2),
    credit_score    char(3),
    customer_ID     integer,
    primary key (card_num),
    foreign key (customer_ID) references customer(ID)
    );
    
CREATE table installment_plan(
    plan            varchar(15),    
    interest        varchar(5),
    duration_days   varchar(3),    
    primary key (plan)
    );
    
CREATE table installment(
    installment_ID  integer GENERATED BY DEFAULT AS IDENTITY,
    customer_ID     integer,
    plan            varchar(15),
    primary key (installment_ID),
    foreign key (customer_ID) references customer(ID),
    foreign key (plan) references installment_plan(plan)
    );
    
CREATE table bank_purchase(
    transaction_ID      integer,
    account_ID          integer,
    confirmation_code   integer GENERATED BY DEFAULT AS IDENTITY
                        (START WITH 190001 increment by 1),
    primary key (transaction_ID),
    foreign key (transaction_ID) references purchase(transaction_ID),
    foreign key (account_ID) references bank_account(account_ID)
);

CREATE table credit_card_purchase(
    transaction_ID      integer,
    fee_amount          decimal(5, 2),
    card_num            char(16),
    primary key (transaction_ID),
    foreign key (transaction_ID) references purchase(transaction_ID),
    foreign key (card_num) references credit_card(card_num)
);

CREATE table installment_purchase(
    transaction_ID      integer,
    installment_ID      integer,
    plan                varchar(15),
    primary key (transaction_ID),
    foreign key (installment_ID) references installment(installment_ID),
    foreign key (plan) references installment_plan(plan),
    foreign key (transaction_ID) references purchase(transaction_ID)
);

